import{r as a,k as p}from"../../../assets/index-chunk.js";import{t as s}from"../../../assets/index-chunk3.js";import{s as d}from"../../../assets/index-chunk5.js";import{p as u}from"../../../assets/index-chunk4.js";import{N as g}from"../chip.js";import"../../../assets/index-chunk2.js";const h=":host{--ngc-chip-disabled-color: var(--color-neutral-50);--ngc-chip-color: var(--color-neutral-70);--ngc-chip-background-color: var(--color-background-primary);--ngc-chip-hover-background-color: var(--color-neutral-20);--ngc-chip-active-background-color: var(--color-neutral-30);--ngc-chip-border-radius: 3rem;--ngc-chip-padding: .25rem .75rem;--ngc-chip-font-size: .9375rem;--ngc-chip-border: none}",b=".gator-chip{background-color:var(--ngc-chip-background-color);border-radius:var(--ngc-chip-border-radius);display:inline-block;padding:var(--ngc-chip-padding);font-size:var(--ngc-chip-font-size);border:var(--ngc-chip-border);color:var(--color-neutral-70)}button:hover{background-color:var(--ngc-chip-hover-background-color);cursor:pointer}button:active{background-color:var(--ngc-chip-active-background-color)}button:disabled{cursor:not-allowed;color:var(--color-neutral-70);outline:1px solid var(--color-neutral-40, #BFBFBF);background:var(--color-neutral-10, #F7F7F7)}.gator-chip__read-only{cursor:default!important}.gator-chip__read-only:active{background-color:var(--ngc-chip-background-color)}";var v=Object.defineProperty,m=Object.getOwnPropertyDescriptor,k=(l,o,n,c)=>{for(var r=c>1?void 0:c?m(o,n):o,t=l.length-1,e;t>=0;t--)(e=l[t])&&(r=(c?e(o,n,r):e(r))||r);return c&&r&&v(o,n,r),r};let i=class extends g{render(){return this.readonly?this.readonlyChipMarkup:this.chipMarkup}get chipMarkup(){return p`
            <button class="gator-chip" ?disabled="${this.disabled}">
                <slot></slot>
            </button>
        `}get readonlyChipMarkup(){return p`
            <button class="gator-chip gator-chip__read-only" ?disabled="${this.disabled}">
                <slot></slot>
            </button>
        `}};i.styles=[a(h),a(b),a(u),a(d)];i=k([s("ngc-chip")],i);export{i as N};
