import{N as g}from"../../alert.js";import{r as c,k as l}from"../../../../assets/index-chunk.js";import{t as p}from"../../../../assets/index-chunk3.js";import{p as f}from"../../../../assets/index-chunk4.js";import{s as m}from"../../../../assets/index-chunk5.js";import"../../../icon/gator/icon.gator.js";import"../../../icon/gator/templates/balloons.js";import"../../../icon/gator/templates/exit-circle.js";import"../../../icon/gator/templates/info.js";import"../../../icon/gator/templates/warning.js";import"../../../icon/gator/templates/check-circle.js";import"../../../icon/gator/templates/restricted.js";import"../../../icon/gator/templates/checkbox.js";import"../../../icon/gator/templates/checkbox-selected.js";import"../../../icon/gator/templates/radio.js";import"../../../icon/gator/templates/radio-selected.js";import"../../../../assets/index-chunk2.js";import"../../../icon/icon-registry.js";const d=".gator-alert{display:flex;padding:24px;margin-bottom:20px;border-radius:1rem;align-content:center;flex-direction:row;font-size:17px;font-family:var(--ngc-font-family)}.gator-alert_icon{margin-right:10px;display:flex;flex-direction:column;justify-content:center}.gator-alert_icon ngc-icon{--ngc-icon-display: flex}.gator-alert_actions{display:flex;flex-direction:column;justify-content:center;margin-left:auto}.gator-alert_content{display:flex;flex-direction:column;justify-content:center}.gator-alert_info{border:1px solid var(--color-stroke-primary);background:var(--color-surface-secondary)}.gator-alert_warning{border:1px solid var(--color-stroke-warning);background:var(--color-surface-warning);--ngc-icon-color: var(--color-icon-warning)}.gator-alert_error{border:1px solid var(--color-stroke-error-weak);background:var(--color-surface-error);--ngc-icon-color: var(--color-icon-error)}.gator-alert_success{border:1px solid var(--color-stroke-success);background:var(--color-surface-success);--ngc-icon-color: var(--color-icon-success)}.gator-alert_inverse{border:1px solid var(--color-stroke-primary)}";var u=Object.defineProperty,v=Object.getOwnPropertyDescriptor,_=(r,e,a,t)=>{for(var o=t>1?void 0:t?v(e,a):e,i=r.length-1,n;i>=0;i--)(n=r[i])&&(o=(t?n(e,a,o):n(o))||o);return t&&o&&u(e,a,o),o};let s=class extends g{render(){return l`
            <div class="gator-alert ${this.variantClass}" role="status">
                <div class="gator-alert_icon">
                    ${this.iconMarkup}
                </div>
                <div class="gator-alert_content">
                    <slot></slot>
                </div>
                <div class="gator-alert_actions">
                    <slot name="actions"></slot>
                </div>
            </div>
        `}get variantClass(){switch(this.variant){case"info":return"gator-alert_info";case"warning":return"gator-alert_warning";case"error":return"gator-alert_error";case"success":return"gator-alert_success";case"inverse":return"gator-alert_inverse";default:return"gator-alert_info"}}get iconMarkup(){let r="info";switch(this.variant){case"info":r="info";break;case"warning":r="warning";break;case"error":r="restricted";break;case"success":r="check-circle";break;case"inverse":r="info";break}return l`<ngc-icon name="${r}" label="${r}"></ngc-icon>`}};s.styles=[c(d),c(f),c(m)];s=_([p("ngc-alert")],s);
